version: '3.1'
services:
  ansible:
    build: .
    volumes:
      - ./workspace:/workspace
    networks:
      - default
    tty: true
    entrypoint: bash -c "bash /workspace/entrypoint.sh && /bin/bash"
networks:
  default:
    external:
      name: br0