- name: mkdir virtual host root directory
  file:
    path: "/var/www/{{ commons.rootdirectory }}"
    state: directory
    owner: "{{ permission.adminuser }}"
    group: "{{ permission.adminuser }}"
    mode: 0755
    recurse: no
- name: mkdir web
  file:
    path: "/var/www/{{ commons.rootdirectory }}/web"
    state: directory
    owner: apache
    group: apache
    mode: 0775
    recurse: no
- name: Setup Apache conffile
  template:
    src: ../templates/apache/vhost.conf.j2
    dest: "/etc/httpd/conf.d/{{ commons.rootdirectory }}.conf"
    mode: '0644'
- name: Reload httpd conf
  systemd:
    name: httpd.service
    state: reloaded
    daemon_reload: yes