- name: Settings vsftpd user_list
  blockinfile:
    path: /etc/vsftpd/user_list
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE basic setup: {{ ftp.username }}"
    block: "{{ ftp.username }}"
- name: Settings vsftpd user_conf
  blockinfile:
    path: "/etc/vsftpd/user_conf/{{ ftp.username }}"
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE basic setup: {{ ftp.username }}"
    block: "local_root=/var/www/{{ commons.rootdirectory }}"
- name: Restart vsftpd
  systemd:
    name: vsftpd.service
    state: restarted
    daemon_reload: yes