- name: Settings vsftpd and httpd

  become: yes
  become_user: "{{ permission.adminuser }}"
  become_method: su

  hosts:
    - add_vhost_servers

  vars_files: ./vars/param_vars.yml

  tasks:
    - name: Add Linux User
      include_tasks: ./tasks/add_user.yml
      vars:
        user: "{{ ftp.username }}"
        passwd: "{{ ftp.password }}"
    - name: Settings vsftpd user_list and user_conf
      include_tasks: ./tasks/vsftpd_user_settings.yml
      vars:
        user: "{{ ftp.username }}"
        directory: "{{ commons.rootdirectory }}"
    - name: Setup Apache conffile
      include_tasks: ./tasks/apache_settings.yml
      vars:
        directory: "{{ commons.rootdirectory }}"
        url: "{{ apache.domain }}"
        ip: "{{ apache.ipaddress }}"
        portnumber: "{{ apache.portnum }}"